import React from "react";
import Head from "next/head";
import { auth, provider } from "../Components/Config";
import { signInWithPopup } from "firebase/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import { useRouter } from "next/router";

const index = () => {
  const loginwithgoogle = () => {
    signInWithPopup(auth, provider);
  };

  const [user, loading] = new useAuthState(auth);
  const router = useRouter();

  if (loading) {
    return <div className="center-word font-bold text-2xl">Loading....</div>;
  }

  if (user) {
    router.push("/Dashboard");
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="conatiner mx-auto ">
        <h1 className="text-2xl tracking-widest center-heading">
          Hello World!!
        </h1>
        <button
          className="center-word bg-blue-700 text-white font-bold py-2 px-4 rounded-full tracking-widest"
          onClick={loginwithgoogle}
        >
          Login with Google
        </button>
      </div>
    </>
  );
};

export default index;
